name: Create Jekyll Blog Post

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Post title"
        required: true
      category:
        description: "Select a category"
        required: true
        type: choice
        options:
          - tech
          - lifestyle
          - travel
          - uncategorized

           formatting •  images •  links •  math •  code •  blockquotes •  external-services

      tags:
        description: "Select a tag (comma-separated)"
        required: true
        type: choice
        options:
          - tutorial
          - opinion
          - review
          - guide

jobs:
  create-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read categories and tags
        run: |
          CATEGORIES=$(cat _data/categories.yml | xargs | sed 's/ /, /g')
          TAGS=$(cat _data/tags.yml | xargs | sed 's/ /, /g')
        id: categories_tags

      - name: Generate new post
        run: |
          TITLE="${{ github.event.inputs.title }}"
          CATEGORY="${{ github.event.inputs.category }}"
          TAGS="${{ github.event.inputs.tags }}"
          DATE=$(date +"%Y-%m-%d %H:%M:%S")
          FILENAME="_posts/$(date +'%Y%m%d')-$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g' | sed 's/[^a-z0-9-]//g').md"

          cat _templates/post-template.md | \
            sed "s/{{date}}/$DATE/" | \
            sed "s/Your Title Here/$TITLE/" | \
            sed "s/\[category1, category2\]/[$CATEGORY]/" | \
            sed "s/\[tag1, tag2\]/[$TAGS]/" \
            > $FILENAME

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add $FILENAME
          git commit -m "Create new post: $TITLE"
          git push

